const { getTimeBasedGreeting, formatDate } = require('../../utils/helpers');

function generateTextContent(articles, toName) {
  let content = `${getTimeBasedGreeting()} ${toName},\n\n`;
  content += "Here's your curated summary of trending marketing news:\n\n";

  articles.forEach((article, index) => {
    content += `📖 ${index + 1}. ${article.title}\n`;
    content += `   📍 Source: ${article.source}\n`;
    content += `   🏷️  Category: ${article.category}\n`;
    content += `   📅 Published: ${formatDate(article.publishedAt, 'short')}\n`;
    content += `   📝 Summary: ${article.summary}\n`;
    content += `   🔗 Read more: ${article.url}\n\n`;
  });

  content +=
    "This digest was automatically generated by NewsCurate AI\n" +
    "To adjust your preferences, please contact your administrator.";

  return content;
}

function generateHtmlContent(articles, toName) {
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; color: white; }
        .content { padding: 20px; }
        .article { margin-bottom: 25px; padding-bottom: 25px; border-bottom: 1px solid #eee; }
        .article-title { font-size: 18px; font-weight: bold; margin-bottom: 10px; color: #2c3e50; }
        .article-meta { color: #7f8c8d; font-size: 14px; margin-bottom: 10px; display: flex; flex-wrap: wrap; gap: 10px; }
        .meta-item { display: flex; align-items: center; }
        .article-summary { margin-bottom: 15px; line-height: 1.6; }
        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #666; }
        a { color: #3498db; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .quality-badge { 
          display: inline-block; 
          padding: 3px 8px; 
          border-radius: 12px; 
          font-size: 12px; 
          font-weight: bold; 
          margin-left: 8px;
        }
        .quality-high { background-color: #2ecc71; color: white; }
        .quality-medium { background-color: #f39c12; color: white; }
        .quality-low { background-color: #e74c3c; color: white; }
        .category-tag {
          display: inline-block;
          padding: 3px 8px;
          border-radius: 4px;
          background-color: #eaf2f8;
          color: #3498db;
          font-size: 12px;
          margin-right: 5px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>📰 Your Daily NewsCurate AI Digest</h1>
        <p>${new Date().toDateString()}</p>
      </div>
      <div class="content">
        <p>${getTimeBasedGreeting()} ${toName},</p>
        <p>Here's your curated summary of trending marketing news:</p>
  `;
  
  articles.forEach((article, index) => {
    html += `
      <div class="article">
        <div class="article-title">${index + 1}. ${article.title}</div>
        <div class="article-meta">
          <span class="meta-item">📍 ${article.source}</span>
          <span class="meta-item">
            <span class="category-tag">${article.category}</span>
          </span>
          <span class="meta-item">📅 ${formatDate(article.publishedAt, 'short')}</span>
          <span class="meta-item">
            Quality: <span class="quality-badge quality-${article.quality}">${article.quality}</span>
          </span>
        </div>
        <div class="article-summary">
          <strong>Summary:</strong> ${article.summary}
        </div>
        <div>
          <a href="${article.url}" target="_blank">🔗 Read full article</a>
        </div>
      </div>
    `;
  });
  
  html += `
      </div>
      <div class="footer">
        <p>This digest was automatically generated by NewsCurate AI</p>
        <p>To adjust your preferences, please contact your administrator.</p>
      </div>
    </body>
    </html>
  `;
  
  return html;
}

module.exports = {
  generateTextContent,
  generateHtmlContent
};